//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int pr_id { get; set; }
        public string pr_name { get; set; }
        public string pr_image { get; set; }
        public string pr_descr { get; set; }
        public Nullable<int> pr_price { get; set; }
        public Nullable<int> pr_fk_ct { get; set; }
        public Nullable<int> pr_fk_user { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
